/* Generated by scripts/make-catalog.mjs from «قائمة المنتجات محدثة.xlsx» + «list of products.xlsx».
   Do not edit by hand — regenerate when the merchant's list changes. */

import type { Product } from "./catalog-types.ts";

export const DEFAULT_CATALOG: Product[] = [
  {
    "id": "1280807828",
    "sallaId": "1280807828",
    "name": "كرتون عصير عنب أحمر  ceres - لتر (12 حبة)",
    "sku": "6001240102114",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/5ff8474e-e24c-4baf-8e3c-141063c5c497-1000x1000-gH51aHZiRDsNasV35TnQsbjO2o9xvBxH5e1VtWXK.png"
    ],
    "price": 135,
    "cost": 84,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "272730369",
    "sallaId": "272730369",
    "name": "كرتون عصير عنب أبيض ceres - لتر (12 حبة)",
    "sku": "6001240102084",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/77fa025d-3325-4077-9880-e3c4a84a104e-1000x754.07925407925-NvKdiTgqbmlwEpKQn1o3ucEM2jOXU3NrE94rXZuU.png"
    ],
    "price": 135,
    "cost": 84,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "346768506",
    "sallaId": "346768506",
    "name": "شاي ماتشا 150g",
    "sku": "6971291060131",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/a7d6b364-f542-4f8a-9a21-68978efd5dee-1000x1000-i3WYI8LzclT0ybVjnzeWsWu01JkExOC4WKHpn1Mh.jpg,https://cdn.salla.sa/qQeReA/714ae6af-e0b2-4345-9f02-c6c2a85281c3-1000x1000-iPdx7is8FH22C1dlV9DAF7uKMdwhkrgAaZAdeqwP.jpg,https://cdn.salla.sa/qQeReA/fff245df-de1a-4bc5-b575-1c7dce2981aa-1000x1000-9IKwIXSkT0uENpwmL9WGqTx4G0kbKSNrWGHA93BL.jpg"
    ],
    "price": 69,
    "cost": 35.56,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "1998432436",
    "sallaId": "1998432436",
    "name": "كرتون قهوة دانكن دارك مطحون ( 6 اكياس ) - 311 جرام",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/210993b8-620b-4285-a1a4-e02f877067fa-1000x1000-IVKnEtnyiHY50jNbkV9bjE1VmzpBN05o5sQUqzTl.png"
    ],
    "price": 299,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "234409488",
    "sallaId": "234409488",
    "name": "25 كوب ورقي من تصميم قوت",
    "sku": "0002",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/a7cbdcb3-7573-40ef-815a-f3575c402975-1000x1000-VRqe6QDcAIenkbbNqmKG4O8bYTi0rbmm44mONeVm.jpg"
    ],
    "price": 17.9,
    "cost": 10,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "200024702",
    "sallaId": "200024702",
    "name": "50 كوب ورقي من تصميم قوت",
    "sku": "0003",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/f6c00bcf-4299-4d3f-b085-69e9ab929edd-1000x1000-XAh4XSlHKKTRVBJbzHdRnthLTQ68sSf6rqi7KI8z.jpg"
    ],
    "price": 32.5,
    "cost": 20,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "1466594937",
    "sallaId": "1466594937",
    "name": "10 أكواب ورقية من تصميم قوت",
    "sku": "0004",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/1debfd2d-e83b-4e03-a3f3-60c481463ad7-1000x1000-20LkGjt7hZA6UM7BaR8lxtPGzqNL124818dgRltd.jpg"
    ],
    "price": 12,
    "cost": 4,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "998383941",
    "sallaId": "998383941",
    "name": "استكر شيت من تصميم قوت",
    "sku": "0007",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/6816ff1a-1529-4abf-9d24-519528856bab-712.47625079164x1000-aKoj3DP0uT7jLLKqJrc98NleiP4615XYaNhi3rq0.jpg"
    ],
    "price": 1.5,
    "cost": 0.5,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "418965942",
    "sallaId": "418965942",
    "name": "اوتلي مشروب الشوفان 1 لتر",
    "sku": "7394376621642",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/b925fce0-b997-43a6-b9cb-9973f10e750f-1000x1000-V4jn73QOVmdHN7pPuWSZZcfC4XnLQUo6sd0cio8o.png"
    ],
    "price": 21.99,
    "cost": 12,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "1473768591",
    "sallaId": "1473768591",
    "name": "بكج الجمعات",
    "sku": "2020202020",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/0393d2e7-b07e-4d4e-8032-8c04d55ca57d-1000x1000-DC0QZvSgAGAdxIqqI2fIqoFa2Hr6UMMNy3tSp5PB.jpg,https://cdn.salla.sa/qQeReA/846783ae-9805-4396-9618-22200e8f1f47-1000x990.22222222222-d1MaNOvwDNYnVjOHRhs66VvVkQs2MKk9tbL1WuiT.jpg,https://cdn.salla.sa/qQeReA/895a2092-3699-4ad9-b437-5be04e320b9f-996.45704162976x1000-5p8tHIZmlX2cMhZXu9Pxu1EC57ZYQiKhNllYYQ3y.jpg"
    ],
    "price": 89,
    "cost": 57,
    "status": "available",
    "variants": [
      {
        "id": "p10:v1",
        "groupName": "نوع الحليب",
        "groupIndex": 1,
        "groupType": "image",
        "value": "مشروب اوتسايد",
        "imageUrl": "https://cdn.salla.sa/qQeReA/018311ff-909d-4da0-a04f-0fd819e5e1b8-1000x1000-qr5RyovI83KmSpRczBWH4FkY5RxWsTkGoIGIJ5Gt.jpg",
        "sku": "8997240600041",
        "price": 88,
        "stock": 0
      },
      {
        "id": "p10:v2",
        "groupName": "نوع الحليب",
        "groupIndex": 1,
        "groupType": "image",
        "value": "مشروب اوتلي",
        "imageUrl": "https://cdn.salla.sa/qQeReA/e0800888-5a93-437b-a8d9-344e2e2ed474-1000x1000-hKHY9tBc7BGHo1BIJuzyuFNzHp4BdNZFoOAzcH64.png",
        "sku": "7394376621642",
        "price": 88,
        "stock": 0
      }
    ],
    "isBundle": true,
    "hasBundleRule": false
  },
  {
    "id": "1839698691",
    "sallaId": "1839698691",
    "name": "5 أظرف قهوة التقطير المختصة كولمبية قوت",
    "sku": "020203",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/34e37708-10c6-438b-bbae-3870694baf9b-1000x1000-JFSBL3HHqIQV32vEuXrAHqARcTVqps9USg6SWVL7.png,https://cdn.salla.sa/qQeReA/980bb4fa-42f0-47ae-82c1-425081570110-1000x1000-wKwPXIBbYlB6ZJ1hyv4F2vVmdGENo4ahytte70y9.png,https://cdn.salla.sa/qQeReA/dab74716-1a88-4770-8cd0-20d47604f7e3-1000x1000-CXmpvBmfU0We4iIHfTCVIwuaWYUKggpNehEJ3orH.png"
    ],
    "price": 29.99,
    "cost": 14,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "2124083404",
    "sallaId": "2124083404",
    "name": "5 أظرف قهوة التقطير المختصة أثيوبية قوت",
    "sku": "23948",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/883127ba-7f28-4ecc-9782-e9d20c01a783-1000x1000-dI75pbc6y1D6IhaYyB7XD4wAkMWuXrn6Cuk6Fgpr.png,https://cdn.salla.sa/qQeReA/0a8ec68a-6446-4ecb-91e0-b828f847b191-1000x1000-N9blxY3lHR0vFIukjpfmevV3DgPHfpcnXDCZEIIz.png,https://cdn.salla.sa/qQeReA/afb6ca92-0482-4e86-80c9-faacaa2d24e4-1000x1000-OkntZRUT0A6LBSmQ14OeboSitusKQITbIn8lBiVk.png"
    ],
    "price": 29.99,
    "cost": 14,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "225784603",
    "sallaId": "225784603",
    "name": "اوتسايد مشروب الشوفان 1 لتر",
    "sku": "8997240600041",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/43f5d35b-da37-445e-817d-fa2b91a1974b-1000x1000-Y1Z8gN6lS1n0zCqMMF4zAXz8pZ4Ti0g69xUookFd.png"
    ],
    "price": 21.99,
    "cost": 12,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "256574347",
    "sallaId": "256574347",
    "name": "ويسك وملعقتين خشبية",
    "sku": "00031",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/4ea3e576-8b74-4aca-9e52-ce5287580c76-1000x949.49494949495-UKc4kHAgtKFNa4exN7ubN71RVQGEwxTEFbYQUSE6.png"
    ],
    "price": 21.99,
    "cost": 12,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "233085684",
    "sallaId": "233085684",
    "name": "استكر شيت رمضاني",
    "sku": "00036",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/6fe972e5-27eb-4cad-90ca-e822a264f63f-1000x1000-Ozkt8Ewo86aPa2DkEoGZdqA2c1UmYdFXKcnuBimK.png"
    ],
    "price": 1.5,
    "cost": 0.5,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "750306119",
    "sallaId": "750306119",
    "name": "بكج الماتشا",
    "sku": "00055",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/7134034a-bf68-41f6-a8b2-75c679249c0f-1000x1000-Akty31Hwb2IYagBqfD76dhVyTnODP3AZWJ7v1Lbi.jpg,https://cdn.salla.sa/qQeReA/7a168349-02d7-419c-b301-760efee00fa0-1000x1000-eEqlEdtt8aSef4CkKmo4axLIa6NeYSMxJnx5OaJi.jpg"
    ],
    "price": 85.99,
    "cost": 46.16,
    "status": "available",
    "variants": [],
    "isBundle": true,
    "hasBundleRule": false
  },
  {
    "id": "909069867",
    "sallaId": "909069867",
    "name": "ملعقة ماتشا",
    "sku": "00060",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/7fe97534-5cff-485c-917f-e6c70f6d454f-1000x1000-1sKrIcAPsBb9vCMIk900ofvL9TngF0JsQaURUK2L.jpg"
    ],
    "price": 9,
    "cost": 1.6,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "1921208373",
    "sallaId": "1921208373",
    "name": "25 كوب ورقي تصميم قوت",
    "sku": "00052",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/c4716170-eff7-40f4-a3ad-ff5855e2996d-1000x1000-s1hQ5ZJb68M0oze9BFfjZsgsbe1gHC0hA1ezcTjz.jpg"
    ],
    "price": 17.9,
    "cost": 10,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "1262368251",
    "sallaId": "1262368251",
    "name": "بكج ال 99",
    "sku": "00034",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/995fe75b-4724-40e5-be74-91b7024df647-1000x1000-PolOHwKTZc7n85RxSOhdjm8wJbSiorbqmaHXwk1n.jpg,https://cdn.salla.sa/qQeReA/36b6792f-791c-4910-a5a9-175174ad5fd9-1000x1000-mzDOVg7bUtpTyDegjWTqI1kWoTp9BPbghpTu0Cdf.jpg,https://cdn.salla.sa/qQeReA/73ab8459-d940-4549-b912-becad1cff712-1000x1000-AWErFNMk1SkR3rO4wF2R1t0VYnYsPvJf8OIJBrSI.jpg,https://cdn.salla.sa/qQeReA/babfeb19-646b-4743-b509-b4d0e5be6f86-1000x1000-NUdAgz5cD9f1nvOBUKmyeAYsHg7cDfnPwy9yjfOZ.jpg"
    ],
    "price": 99,
    "cost": 59,
    "status": "available",
    "variants": [
      {
        "id": "p21:v1",
        "groupName": "نوع الحليب",
        "groupIndex": 1,
        "groupType": "image",
        "value": "مشروب اوتسايد",
        "imageUrl": "https://cdn.salla.sa/qQeReA/73ab8459-d940-4549-b912-becad1cff712-1000x1000-AWErFNMk1SkR3rO4wF2R1t0VYnYsPvJf8OIJBrSI.jpg",
        "price": 99,
        "stock": 0
      },
      {
        "id": "p21:v2",
        "groupName": "نوع الحليب",
        "groupIndex": 1,
        "groupType": "image",
        "value": "مشروب اوتلي",
        "imageUrl": "https://cdn.salla.sa/qQeReA/babfeb19-646b-4743-b509-b4d0e5be6f86-1000x1000-NUdAgz5cD9f1nvOBUKmyeAYsHg7cDfnPwy9yjfOZ.jpg",
        "price": 99,
        "stock": 0
      }
    ],
    "isBundle": true,
    "hasBundleRule": false
  },
  {
    "id": "2107150280",
    "sallaId": "2107150280",
    "name": "ادوات ماتشا 4 قطع ابيض",
    "sku": "4052WH",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/024bf1c2-f4e6-40c0-b313-1fb577d32411-1000x1000-hjvLV8icFaPD5M8kFyPrEvnhRlf6ZV67ES5SH1Bu.jpg"
    ],
    "price": 79.99,
    "cost": 31.13,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "889300871",
    "sallaId": "889300871",
    "name": "ادوات ماتشا 4 قطع اسود",
    "sku": "4052BK",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/71f69874-03a5-4bbf-af1e-cbcebb3e9218-1000x1000-RRilCw1W1pTdbNbF6An1L30Ztj8DPccDNC7bEJyu.jpg"
    ],
    "price": 79.99,
    "cost": 31.13,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "3081222",
    "sallaId": "3081222",
    "name": "مق لون اسود 355 ملي",
    "sku": "3052BK",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/dda1e3b6-2787-4198-a8a7-1e995149817d-1000x1000-HxVqqd92LIh6qFhtgOoYLVr4vstYpfv5gpFwy4c3.jpg"
    ],
    "price": 29,
    "cost": 8,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "1794649324",
    "sallaId": "1794649324",
    "name": "مق لون ابيض 355 ملي",
    "sku": "3052WH",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/4f5f21a6-d8f0-47d9-af88-be3f56730629-1000x1000-Ne2qxn0na9jdpbOIzPMN0p0Ec746dEA6oLY3wsh9.jpg"
    ],
    "price": 29,
    "cost": 8,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "1668099490",
    "sallaId": "1668099490",
    "name": "حافظه بتفريغ الهواء 900ملي",
    "sku": "011",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/d3ddf0cd-0ea7-48f6-b03c-ba20cdb89711-1000x1000-aMrcaU2MJR0TUPihOEup6vJPnggjyD5USa0sCJmb.jpg,https://cdn.salla.sa/qQeReA/cb842291-7e70-4d87-ad2e-7b1a3c572a62-1000x1000-f5bw1AvPl7bNa5rI3Cn8wHKeFQdVzZ6YTaLpiek9.jpg"
    ],
    "price": 32,
    "cost": 9.45,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "1941886031",
    "sallaId": "1941886031",
    "name": "ملعقة معيارية 15 ملي",
    "sku": "3059",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/41e9a104-4c83-4b8e-9699-5274053977c5-1000x1000-nGEXdXGHa0kl7VBdKvx9gd5COMdiAlhpZ8n3v5r8.jpg"
    ],
    "price": 17,
    "cost": 4.5,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "1277332160",
    "sallaId": "1277332160",
    "name": "كوب سيراميك 4043",
    "sku": "4043",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/050d2db4-5b7b-48c2-a1d9-f4d4b8e7d181-1000x1000-Ts17zLvbIcuSI2Ar05yeXJjC7iJwHTBqFIC0bqri.jpg"
    ],
    "price": 23,
    "cost": 7,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "1362732413",
    "sallaId": "1362732413",
    "name": "كوب سيراميك 4055",
    "sku": "4055",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/0ae04c7c-005a-48fa-a193-f7e788a66188-1000x1000-x4LQcLqowvPcheO9Tl8037mn08L86BCY6bC1Ub19.jpg"
    ],
    "price": 23,
    "cost": 6,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "93475981",
    "sallaId": "93475981",
    "name": "كوب سيراميك 4056",
    "sku": "4056",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/74c7bde0-8809-4162-ba59-745622b13fb1-1000x1000-DWLxUdDoYK2K9MvmjxfGsQkk2knKtYvX6vXEuRfw.jpg"
    ],
    "price": 23,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "207230157",
    "sallaId": "207230157",
    "name": "كوب سيراميك 4057",
    "sku": "4057",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/7d430f70-d6d4-4373-8c87-bc2dbbe28b64-1000x1000-dUxJ00rfYKLajoXMhtvoINEbkuPs6OBxAmno4Khr.jpg"
    ],
    "price": 23,
    "cost": 6,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "325754228",
    "sallaId": "325754228",
    "name": "كوب سيراميك 4058",
    "sku": "4058",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/a531d5d2-6ed2-4af1-9d68-6efa7b6fde72-1000x1000-0PpdMeH26sDTOXnHzzJTPINwtO24WoOlBnDvg27o.jpg"
    ],
    "price": 23,
    "cost": 6,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "1584424912",
    "sallaId": "1584424912",
    "name": "بكج ماتشا وادواتها أبيض",
    "sku": "222333",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/6b11acd1-00b5-4618-96ec-f58816a74000-1000x1000-5oQ8jfzbiV1tKnugkypUmcBtGmJCnPoZjxZi83ju.jpg,https://cdn.salla.sa/qQeReA/270a335b-0314-4459-83f7-a9fba4100e08-1000x1000-93GgvXAxq9Fec6y2T1NPJs4kRQ0jBahhyGD0Atqn.jpg"
    ],
    "price": 135,
    "cost": 71.58,
    "status": "available",
    "variants": [],
    "isBundle": true,
    "hasBundleRule": false
  },
  {
    "id": "170455920",
    "sallaId": "170455920",
    "name": "بكج ماتشا وادواتها اسود",
    "sku": "02356",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/84480ff3-b7e4-432f-9b09-a863a3d67c52-1000x1000-5YekkScuftwVqsxQGPEMYjvGlvCoM6NcyKxaVPMI.jpg,https://cdn.salla.sa/qQeReA/764b0ddd-70e8-4482-8512-58409892a5bc-1000x1000-Cpt6vxofS025xPV9oUmz46Ok9ncfM7JtSoStMUQ1.jpg"
    ],
    "price": 135,
    "cost": 71.58,
    "status": "available",
    "variants": [],
    "isBundle": true,
    "hasBundleRule": false
  },
  {
    "id": "746155360",
    "sallaId": "746155360",
    "name": "بكج القهوة مع مق",
    "sku": "03215",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/843ef00e-87df-4b5a-9ae3-f51b6a7a4ed7-1000x1000-fALAMVjRhUQ3JPI1lhwTIEl4Fb8UrgGroBZiYLKr.jpg,https://cdn.salla.sa/qQeReA/185cbb3c-8d96-4cfd-8e6f-634df71c037f-1000x1000-JI35VRnatszeRoV7AZxb5rqMJhZUC9HyClFs4Muo.jpg,https://cdn.salla.sa/qQeReA/32d50e49-da2a-4c7a-b8ae-afdbd6d8bc6c-1000x1000-Ha88yesMvzzvLEA0uOUsOxEvUxIvjF3BLVvbKzb6.jpg,https://cdn.salla.sa/qQeReA/5e926757-d5d7-4c50-ab61-fd367d35c8f8-1000x1000-vkBZ2JJLJIbFr7jSQzwISRKG3bBVhwckXhowWioY.jpg,https://cdn.salla.sa/qQeReA/7618e845-820b-430f-9119-8d532b33c065-1000x1000-dna7BrGRzMZZOXuVBAapdlJ3wv3HhFB3CJmdMBSp.jpg,https://cdn.salla.sa/qQeReA/9fbc416d-aec7-48d4-85d2-fe591f8f3f82-1000x1000-LX4HAvPJiyxkMb2Y1NjUhwfGVWF6aYdmcbLoivB0.jpg"
    ],
    "price": 88.98,
    "cost": 39.15,
    "status": "available",
    "variants": [
      {
        "id": "p37:v1",
        "groupName": "لون المق",
        "groupIndex": 1,
        "groupType": "image",
        "value": "مق لون اسود",
        "imageUrl": "https://cdn.salla.sa/qQeReA/185cbb3c-8d96-4cfd-8e6f-634df71c037f-1000x1000-JI35VRnatszeRoV7AZxb5rqMJhZUC9HyClFs4Muo.jpg",
        "price": 78.99,
        "stock": 30
      },
      {
        "id": "p37:v2",
        "groupName": "لون المق",
        "groupIndex": 1,
        "groupType": "image",
        "value": "مق لون ابيض",
        "imageUrl": "https://cdn.salla.sa/qQeReA/9fbc416d-aec7-48d4-85d2-fe591f8f3f82-1000x1000-LX4HAvPJiyxkMb2Y1NjUhwfGVWF6aYdmcbLoivB0.jpg",
        "price": 78.99,
        "stock": 6
      }
    ],
    "isBundle": true,
    "hasBundleRule": false
  },
  {
    "id": "175702075",
    "sallaId": "175702075",
    "name": "بكج القهوة - أثيوبي وكولومبي",
    "sku": "CoffeePackage",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/8b143c32-3b6e-4fea-853d-4a4815c00764-1000x1000-ji7r1VnA4qYBP8P3ritPYMhGAfP9mgBUFqPUAJB8.jpg"
    ],
    "price": 59.98,
    "cost": 30.15,
    "status": "available",
    "variants": [],
    "isBundle": true,
    "hasBundleRule": false
  },
  {
    "id": "122056508",
    "sallaId": "122056508",
    "name": "ماتشا احتفالية فاخرة 50 جرام",
    "sku": "021565",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/4ea38f1b-890a-4511-9e0a-f6b370b593e6-1000x1000-h01YXAwiu4C8dTruyblcJyAfwYKYOsiLJXnod5Na.jpg,https://cdn.salla.sa/qQeReA/64350298-04bb-4bcc-b13f-6c12d6dd87a5-1000x1000-KfiRmY7ERG0C8DyIThsqB7NzkaSBt7Gvw8H0LMNe.jpg,https://cdn.salla.sa/qQeReA/b9fbfc2a-6d5f-4b02-bebf-de8393a5a8ed-1000x1000-jtOa7lQOQZF6sYxyNopamoM5MfhMicQhE52XDtBR.jpg,https://cdn.salla.sa/qQeReA/d37be386-4825-46f4-8ed4-5121cb8de205-1000x1000-g9NCRLX8BBxYYveJLZjmUVI5KJS6PS53XnA2DARE.png"
    ],
    "price": 99,
    "cost": 65,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "1232871891",
    "sallaId": "1232871891",
    "name": "استكر شيت من تصميم قوت",
    "sku": "00054",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/73b756a5-8fb8-4ea0-8c69-2fc05cf1f7e5-1000x1000-bCmneBIvx8ztixj9elqGAVoIQjWNQznCCnETNyFJ.png"
    ],
    "price": 1.5,
    "cost": 0.5,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "605921576",
    "sallaId": "605921576",
    "name": "10 أكواب ورقية من تصميم قوت",
    "sku": "00058",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/f7a95910-c089-44e6-a432-1326911cb744-1000x1000-gBcGwhfSyzN63KCL7fuqlfyoXvOVhfIemhQjKVEp.jpg"
    ],
    "price": 12,
    "cost": 4,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "978873704",
    "sallaId": "978873704",
    "name": "10 أكواب ورقية من تصميم قوت",
    "sku": "00051",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/432a4c60-6b6d-466d-9ba7-002a7d18e2b5-1000x1000-PhzDWdlmjf9JiSHRjTZsTkKHZD5vjuPTFcKBTbE8.jpg"
    ],
    "price": 12,
    "cost": 4,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "1064149925",
    "sallaId": "1064149925",
    "name": "بكج ماتشا احتفالية فاخرة 50 جرام وادواتها اسود",
    "sku": "02314",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/1d8d453e-7c3d-4cf1-9ff5-985ab4359285-1000x1000-O2anXHuYpqQ94u3CE8G9goJiIHwuSy1KpxhzR9zD.jpg,https://cdn.salla.sa/qQeReA/6138b262-4b9a-4c47-881d-d41598f4d12e-1000x1000-EByDnAQ3AmYXVEIyOCvST3FeQAowGak2aI9gzIK5.jpg"
    ],
    "price": 135,
    "status": "available",
    "variants": [],
    "isBundle": true,
    "hasBundleRule": false
  },
  {
    "id": "1956763074",
    "sallaId": "1956763074",
    "name": "بكج ماتشا احتفالية فاخرة 50 جرام وادواتها ابيض",
    "sku": "03178",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/28f40feb-3984-48d3-b9c6-8bb1ff06210d-1000x1000-SbqTjJ0dVm6chZMUrXIG0S0PjgaH7cB95AJ784HF.jpg,https://cdn.salla.sa/qQeReA/a68758d1-c8a9-43e9-b29f-ec097aadbb64-1000x1000-2Nx8IJDYANaeI43cYiSMwiHLz2Nj8HDhMFJ2p8qg.jpg"
    ],
    "price": 135,
    "status": "available",
    "variants": [],
    "isBundle": true,
    "hasBundleRule": false
  },
  {
    "id": "647454057",
    "sallaId": "647454057",
    "name": "بكج ماتشا احفالية فاخرة 50 جرام",
    "sku": "03156",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/a0127b00-b391-4000-9138-0d75c0659616-1000x1000-vhPS9lNzqL3K9go40OBTQPYLRLOkD4GksE9eRdBR.jpg,https://cdn.salla.sa/qQeReA/924a6d6d-f600-4e7f-ba50-587e8bd180e5-1000x1000-EhCjwLdZ0suuZN3LpyyQaB8V7FFMiBJ2ZuIM0csz.jpg"
    ],
    "price": 109,
    "status": "available",
    "variants": [],
    "isBundle": true,
    "hasBundleRule": false
  },
  {
    "id": "1131418886",
    "sallaId": "1131418886",
    "name": "10 أكواب ورقية من تصميم قوت",
    "sku": "014789",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/8aeecbc8-2a75-4ac0-98f7-adc64e2aeeb5-1000x1000-gCpQcLaqIQrOCVmQirl4i7zpOdDtxQum5ygcx2Pg.jpg"
    ],
    "price": 12,
    "cost": 4,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "1781109735",
    "sallaId": "1781109735",
    "name": "25 كوب ورقي تصميم قوت",
    "sku": "02467",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/67e0c222-fa54-4f94-8696-e1b9f65933bb-1000x1000-bEmpgJArpoAPPpN1s89r0nvaRJLs3eiR2JG9DL2j.jpg"
    ],
    "price": 17.9,
    "cost": 10,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "1396279966",
    "sallaId": "1396279966",
    "name": "استكر شيت من تصميم قوت",
    "sku": "21478",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/c62da488-77c9-4b7b-9048-8710e61b333c-1000x1000-WVV1b3kdDU8UGUd9rZuIRnpO9GVaTWel3WWuUfuR.png"
    ],
    "price": 1.5,
    "cost": 0.5,
    "status": "available",
    "variants": [],
    "isBundle": false,
    "hasBundleRule": false
  },
  {
    "id": "74776552",
    "sallaId": "74776552",
    "name": "بكج اليوم الوطني",
    "sku": "Watan96",
    "categories": [],
    "imageUrls": [
      "https://cdn.salla.sa/qQeReA/9b05643c-02c9-4479-91ca-5d0fd41f917e-1000x666.25-UFi44DL7tdSsmeMnrDf90jRUKTCkfAWHEICox6DW.jpg,https://cdn.salla.sa/qQeReA/f7355f55-7de9-4905-adc1-afd5b4cd0095-1000x666.25-l78fxqBK99IZfbMxtSOiocuEIMkWuTx6M8FB36gj.jpg"
    ],
    "price": 96,
    "status": "available",
    "variants": [],
    "isBundle": true,
    "hasBundleRule": false
  }
];
