/**
 * Regenerates src/lib/inventory/bom-default.ts from the merchant's workbook.
 *
 *   node --experimental-strip-types scripts/make-bom.mjs "<path to .xlsx>"
 *
 * The matrix is baked in so جرد الكميات works on a fresh phone with nothing to
 * upload; الإعدادات can still replace it when a recipe changes.
 */
import fs from "node:fs";
import path from "node:path";
import { parseBom } from "../src/lib/inventory/bom.ts";

const src = process.argv[2];
if (!src) {
  console.error("usage: node --experimental-strip-types scripts/make-bom.mjs <workbook>");
  process.exit(1);
}

const XLSX = await import("xlsx");
const wb = XLSX.read(fs.readFileSync(src), { type: "buffer" });

let best = { rows: [], components: [] };
for (const name of wb.SheetNames) {
  const rows = XLSX.utils.sheet_to_json(wb.Sheets[name], { header: 1, raw: true, defval: "" });
  const parsed = parseBom(rows);
  if (parsed.components.length > best.components.length) best = parsed;
}
if (!best.rows.length) throw new Error("no matrix sheet found");

const out = `/* Generated by scripts/make-bom.mjs from «${path.basename(src)}».
   Do not edit by hand — regenerate when the merchant's sheet changes. */

import type { Bom } from "./bom.ts";

export const DEFAULT_BOM: Bom = ${JSON.stringify(best, null, 2)};
`;
fs.writeFileSync("src/lib/inventory/bom-default.ts", out);
console.log(`${best.rows.length} products, ${best.components.length} components`);
