/**
 * Regenerates src/lib/catalog-default.ts from the merchant's exports.
 *
 *   node --experimental-strip-types scripts/make-catalog.mjs \
 *     "<قائمة المنتجات محدثة.xlsx>" ["<full Salla export.xlsx>"]
 *
 * The catalog is baked in because it barely changes and re-uploading it before
 * every batch was pure friction. الإعدادات can still replace it on the device.
 *
 * Two sources, because no single export carries everything:
 *   • the short list — current names, prices and image URLs
 *   • the full Salla export — cost prices and option values, which the short
 *     list drops; matched by SKU, and only used to fill gaps
 */
import fs from "node:fs";
import path from "node:path";
import { importCatalog } from "../src/lib/excel/import.ts";

const [shortPath, fullPath] = process.argv.slice(2);
if (!shortPath) {
  console.error("usage: make-catalog.mjs <short list.xlsx> [full salla export.xlsx]");
  process.exit(1);
}

const XLSX = await import("xlsx");
const sheetRows = (file) => {
  const wb = XLSX.read(fs.readFileSync(file), { type: "buffer" });
  return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], {
    header: 1,
    raw: true,
    defval: "",
  });
};

/** Digits and letters only, no leading zeros — the same rule the app matches on. */
const idKey = (v) =>
  String(v ?? "").replace(/[^0-9A-Za-z]/g, "").replace(/^0+/, "").toLowerCase();

/* ── extras from the full export: cost price and option values ── */
const extras = new Map();
const costByName = new Map();
if (fullPath && fs.existsSync(fullPath)) {
  const rows = sheetRows(fullPath);
  const head = rows[0].map((h) => String(h).trim());
  const costCol = head.indexOf("سعر التكلفة");
  const skuCol = head.indexOf("رمز المنتج sku");
  for (const r of rows.slice(1)) {
    if (String(r[1]).trim() !== "منتج") continue;
    const key = idKey(r[skuCol]);
    if (!key) continue;
    const cost = Number(r[costCol]);
    if (!Number.isFinite(cost) || cost <= 0) continue;
    extras.set(key, { cost });
    // The same product is listed under several SKUs when a printing changes —
    // three sticker sheets, four cup packs — and they cost the same. Keyed by
    // name as well, so a re-issued SKU inherits the cost instead of reading
    // as free.
    const byName = String(r[2] ?? "").trim();
    if (byName && !costByName.has(byName)) costByName.set(byName, cost);
  }

  // Variants come from the importer, which already untangles the export's
  // option columns and attaches them to the right parent.
  const wb = XLSX.read(fs.readFileSync(fullPath), { type: "buffer" });
  const objs = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], {
    defval: null,
    raw: true,
  });
  for (const p of importCatalog(objs).products) {
    if (!p.variants.length) continue;
    const key = idKey(p.sku);
    if (!key) continue;
    extras.set(key, { ...(extras.get(key) ?? {}), variants: p.variants });
  }
}

/* ── the short list is the authority on what exists, and on price ── */
const rows = sheetRows(shortPath);
const head = rows[0].map((h) => String(h).trim());
const col = (name) => head.findIndex((h) => h === name);
const C = {
  id: col("No."),
  type: col("النوع") === -1 ? 1 : col("النوع"),
  name: col("أسم المنتج"),
  image: col("صورة المنتج"),
  price: col("سعر المنتج"),
  sku: col("رمز المنتج sku"),
};

const products = [];
const seen = new Set();
for (const r of rows.slice(1)) {
  // "خيار" rows repeat their parent's name and id; the parent already covers it.
  if (String(r[C.type]).trim() !== "منتج") continue;
  const name = String(r[C.name] ?? "").trim();
  if (!name) continue;
  const sku = String(r[C.sku] ?? "").trim();
  const sallaId = String(r[C.id] ?? "").trim();
  const dedupe = `${sallaId}|${sku}`;
  if (seen.has(dedupe)) continue;
  seen.add(dedupe);

  const extra = extras.get(idKey(sku)) ?? {};
  const cost = extra.cost ?? costByName.get(name);
  const price = Number(r[C.price]);
  const image = String(r[C.image] ?? "").trim();
  products.push({
    id: sallaId || sku || name,
    sallaId: sallaId || undefined,
    name,
    sku: sku || undefined,
    categories: [],
    imageUrls: image ? [image] : [],
    price: Number.isFinite(price) ? price : undefined,
    cost,
    status: "available",
    variants: extra.variants ?? [],
    isBundle: /بكج|باقة|طقم/.test(name),
    hasBundleRule: false,
  });
}

const noCost = products.filter((p) => p.cost === undefined);
const out = `/* Generated by scripts/make-catalog.mjs from «${path.basename(shortPath)}»${
  fullPath ? ` + «${path.basename(fullPath)}»` : ""
}.
   Do not edit by hand — regenerate when the merchant's list changes. */

import type { Product } from "./catalog-types.ts";

export const DEFAULT_CATALOG: Product[] = ${JSON.stringify(products, null, 2)};
`;
fs.writeFileSync("src/lib/catalog-default.ts", out);
console.log(
  `${products.length} products, ${products.length - noCost.length} with a cost price`,
);
if (noCost.length) {
  console.log("no cost yet:");
  for (const p of noCost) console.log(`  · ${p.name} (sku ${p.sku ?? "—"})`);
}
